### ISSUE TITLE
Peer-to-peer-code-review-W5 D4

### ISSUE THREAD

**Issue by ghost** [ReemMohamedAbdelfatah/EgyptJuniorsProgrammingSummit-Capstone-1#2]
### Hi @ReemMohamedAbdelfatah 
Wonderful job so far!

- No linters error
- GitHub workflow followed
- Great design
However, you just need to make a few amends to specific sections:

- The height of the first section needs to be reduced whilst ensuring that the texts do not overlap. kindly reduce it, please
- The footer width has to be adjusted to avoid an overflow outside the body of the page. Kindly, do this, please
- on the featured section, kindly take out the margin-top on the '.speaker_text_container' class.

**Comment by ReemMohamedAbdelfatah** [comment]
Hello @Ade179 ,
thank you for your support. I will fix the issues.
